//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_6__Introduction_to_Entity_Framework_Core_Part_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class countries
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> capital_id { get; set; }
        public Nullable<int> population { get; set; }
        public Nullable<int> area { get; set; }
        public string part_of_the_world { get; set; }
    
        public virtual capitals capitals { get; set; }
        public virtual cities cities { get; set; }
    }
}
