//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_6__Introduction_to_Entity_Framework_Core_Part_3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDbContecs : DbContext
    {
        public TestDbContecs()
            : base("name=TestDbContecs")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<capitals> capitals { get; set; }
        public virtual DbSet<cities> cities { get; set; }
        public virtual DbSet<countries> countries { get; set; }
    }
}
