// <auto-generated />
namespace Entity_Framework_Core_Part_4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Type));
        
        string IMigrationMetadata.Id
        {
            get { return "202303261730207_Type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
